services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: micro_hero_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Зберігаємо логи та зображення
      - ./logs:/app/logs
      - ./static/images:/app/static/images
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

